services:
  _defaults:
    autowire: true
    autoconfigure: true
    
  Flex\Controller\PageController:
    arguments:
      $viewRenderer: '@Flex\View\ViewRenderService'
      $requestStack: '@request_stack' 
    tags:
      - { name: 'controller.service_arguments' }

  Flex\Controller\ActionController:
    tags:
      - { name: 'controller.service_arguments' }

  Flex\Controller\RouteController:
    tags:
      - { name: 'controller.service_arguments' }