services:
  Flex\View\ViewEngineManager: ~
  Flex\View\ViewRenderService:
    arguments:
      $twig: '@twig'
      $projectDir: '%kernel.project_dir%'

  Flex\View\Engine\Twig\Extension\FlexTwigExtension:
    tags:
      - { name: 'twig.extension' }