services:
  _defaults:
    autowire: true
    autoconfigure: true

imports:
  - { resource: 'services/controllers.yaml' }
  - { resource: 'services/routing.yaml' }
  - { resource: 'services/views.yaml' }
  - { resource: 'services/listeners.yaml' }
  - { resource: 'services/twig.yaml' }
